enabled: true
include:
  - md
  # node related:
  - ts
  - mts
  - cts
  - js
  - cjs
  - mjs
  - json
ignores:
  - "package-lock.json"
global_languages:
  # node related only for global search
  #  TODO maybe have a config global retrieval vs global search (can have diff filters, or actually global search could just always be everything)
  - ts
  - mts
  - cts
  - js
  - cjs
  - mjs
